//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingBio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int bookingId { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<System.DateTime> bookingForDate { get; set; }
        public Nullable<System.DateTime> bookingMadeDate { get; set; }
        public Nullable<int> allSeatsId { get; set; }
    
        public virtual AllSeats AllSeats { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
