//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingBio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieShowings
    {
        public int movieShowingsId { get; set; }
        public Nullable<int> loungeId { get; set; }
        public Nullable<int> movieId { get; set; }
        public Nullable<System.DateTime> showingFromDate { get; set; }
        public Nullable<System.DateTime> showToDate { get; set; }
    
        public virtual Lounges Lounges { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
