//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingBio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccounts
    {
        public int userAccountId { get; set; }
        public string accountName { get; set; }
        public string accountPassword { get; set; }
        public Nullable<int> customerId { get; set; }
        public string customerName { get; set; }
        public string phoneNumber { get; set; }
        public string salt { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
